#!/usr/bin/env bash

# ==============================
# Pipeline runner for cleavage site prediction
# Runs two Python scripts in sequence:
#   1. svm-predictor.py <input.fasta>
#   2. make-fragments_V2.py <input.fasta> ../results/predictions.csv
#
# Usage:
#   ./run_pipeline.sh <input.fasta>
# ==============================

# Check input argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <input.fasta>"
    exit 1
fi

INPUT_FASTA="$1"

# Paths to Python scripts
PREDICTOR="scripts/svm-predictor.py"
FRAGMENTS="scripts/make-fragments_V2.py"

# Output file generated by the first script
OUTPUT_CSV="results/predictions.csv"
OUTPUT_frag="results/fragments.fasta"
# Step 1: Run SVM predictor
echo "[1/2] Running SVM predictor..."
python3 "$PREDICTOR" "$INPUT_FASTA"
# Step 2: Generate fragments using predictions
echo "[2/2] Running fragment generator..."
python3 "$FRAGMENTS" "$INPUT_FASTA" "$OUTPUT_CSV" > "$OUTPUT_frag"
echo "Done."
