#!/usr/bin/env python3
import sys
from Bio import SeqIO

# Uso: script.py <input.fasta> <df.csv>
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.fasta> <df.csv>")
        sys.exit(1)

fasta = sys.argv[1]
csv = sys.argv[2]

fasta_dict = {
    str(rec.id): str(rec.seq)
    for rec in SeqIO.parse(fasta, "fasta")
}

frag_dict = {}

with open(csv) as f:
    next(f)

    for row in f:
        row = row.strip()

        if not row:
            continue

        entry, kmer, site, predicted_class, probability, score = row.split(",")

        entry = entry.split("_kmer")[0]

        if fasta_dict.get(entry) and int(predicted_class) == 1:
            frag_dict.setdefault(entry, []).append({
                "site": int(site),
                "probability": float(probability),
                "score": float(score)
            })

for entry, fragments in frag_dict.items():
    seq = fasta_dict[entry]
    fragments.sort(key=lambda x: x["site"])

    full_len = len(seq)

    for i, frag in enumerate(fragments):
        start = frag["site"]

        if i == 0:
            frag_before = seq[:start]

            if frag_before:
                print(
                    f">{entry}\tSITE=[{start}]\tPROBABILITY=[{frag['probability']}]\tSCORE=[{frag['score']}]"
                )
                print(frag_before)

        end = fragments[i + 1]["site"] if i + 1 < len(fragments) else full_len
        frag_after = seq[start:end]

        # Skip single-residue fragments generated by consecutive sites
        if len(frag_after) > 1:
            print(
                f">{entry}\tSITE=[{start}]\tPROBABILITY=[{frag['probability']}]\tSCORE=[{frag['score']}]"
            )
            print(frag_after)
